# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
  fetchgit,
}:
linkFarm "zig-packages" [
  {
    name = "N-V-__8AAPu4vwC_P5AHlL_kEON58uGgrDcJSjGq9Hc5yadh";
    path = fetchzip {
      url = "https://github.com/mackron/miniaudio/archive/refs/tags/0.11.23.zip";
      hash = "sha256-ZrfKw5a3AtIER2btCKWhuvygasNaHNf9EURf1Kv96Vc=";
    };
  }
]
