# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAAF7XwFQf2BoBVQVkTp-NCEFilDqIrtbU9g4WFAg";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-darwin-build/releases/download/v7.0.2-1/ffmpeg-xcframeworks_v7.0.2-1_macos-universal-video-default.tar.gz";
      hash = "sha256-1JZgn9kx5/dYDUYkrBxlgLEJem4ac9nGBOgOtkcDXG8=";
    };
  }
  {
    name = "N-V-__8AACGMBABgKdmDWqNHjOLJ_eVn1c_tDbaxu3r1pkpS";
    path = fetchzip {
      url = "https://icolo.dl.sourceforge.net/project/gnuwin32/patch/2.5.9-7/patch-2.5.9-7-bin.zip?viasf=1";
      hash = "sha256-ZxW1OeP+o5qxGlVvzaEdAOGOk5dv56yabQ+clV3+ZzI=";
    };
  }
  {
    name = "N-V-__8AAIHakgFASykx4lexFZQChFGwWwQ5rDBL5XrOCezh";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-android-build/releases/download/v7.1-3/default-x86_64.zip";
      hash = "sha256-RcnrF6/y+mQw82igFSWklERWUHu+/VqsubrLYSmDPWk=";
    };
  }
  {
    name = "N-V-__8AAIX6uQBMQoqkZK7Ws3HsCwSJf1Z_KLsW4CJx81k3";
    path = fetchzip {
      url = "https://github.com/mackron/miniaudio/archive/refs/tags/0.11.22.zip";
      hash = "sha256-o/7sfBcrhyXEakccOAogQqm8dO4Szj1QSpaIHg6OSt4=";
    };
  }
  {
    name = "N-V-__8AAJ8bbwgQf_QTYTYX75tN42xYTQQ1fdJ652O03odP";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-win32-build/releases/download/latest/ffmpeg-n7.1-latest-win64-lgpl-shared-7.1.zip";
      hash = "sha256-lJGRvx/Z0hDRYX5398D8LbFNK8gCqxFk/Rn+ILJaKcI=";
    };
  }
  {
    name = "N-V-__8AAJVvTwE1vBP2rMMZlc4U5VU8BghEtVkrWGmnQ4Sx";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-android-build/releases/download/v7.1-3/default-armeabi-v7a.zip";
      hash = "sha256-1iNshv70D6bbll7BFqFhGYyG0QSdt2f4NFpfguAQjco=";
    };
  }
  {
    name = "N-V-__8AAMioJQJPsTJkHS5srthHxLC16RaGgAdTIyziK_Bi";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-darwin-build/releases/download/v7.0.2-1/ffmpeg-xcframeworks_v7.0.2-1_ios-universal-video-default.tar.gz";
      hash = "sha256-HAzrMHDER2yjzfMlFVumI3EvYxxiHCvhCFPpwVr9e6k=";
    };
  }
  {
    name = "N-V-__8AAOlodAHGt7-GT4PEp7D9IUyn_s8OrksnPMqZJ7SE";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-android-build/releases/download/v7.1-3/default-arm64-v8a.zip";
      hash = "sha256-jKdprGa/mW4mGvM/0eDttFd1pb5uFzBs4pYUDKaOZuo=";
    };
  }
  {
    name = "N-V-__8AAPFCRgFgwZzHB_MBjLzsyWgI450E1fkIIBTTsOm_";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-android-build/releases/download/v7.1-3/default-x86.zip";
      hash = "sha256-It2qhpve1zt5n4JpM13vLAPBUr5oTjvJod1rmOL8ljw=";
    };
  }
]
