# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAAF7XwFQf2BoBVQVkTp-NCEFilDqIrtbU9g4WFAg";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-darwin-build/releases/download/v7.0.2-1/ffmpeg-xcframeworks_v7.0.2-1_macos-universal-video-default.tar.gz";
      hash = "sha256-1JZgn9kx5/dYDUYkrBxlgLEJem4ac9nGBOgOtkcDXG8=";
    };
  }
  {
    name = "N-V-__8AAIHakgFASykx4lexFZQChFGwWwQ5rDBL5XrOCezh";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-android-build/releases/download/v7.1-3/default-x86_64.jar";
      hash = "sha256-3nVva2ZEzCrWTSgr5BpUqksQgYMAXmLA4FVyqH3k7Tc=";
    };
  }
  {
    name = "N-V-__8AAJ8bbwgQf_QTYTYX75tN42xYTQQ1fdJ652O03odP";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-win32-build/releases/download/latest/ffmpeg-n7.1-latest-win64-lgpl-shared-7.1.zip";
      hash = "sha256-lJGRvx/Z0hDRYX5398D8LbFNK8gCqxFk/Rn+ILJaKcI=";
    };
  }
  {
    name = "N-V-__8AAJVvTwE1vBP2rMMZlc4U5VU8BghEtVkrWGmnQ4Sx";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-android-build/releases/download/v7.1-3/default-armeabi-v7a.jar";
      hash = "sha256-J6WJKp6JwZGrY2+mEGIfhYlgwqett2jJvBiTgWn1fdg=";
    };
  }
  {
    name = "N-V-__8AAMioJQJPsTJkHS5srthHxLC16RaGgAdTIyziK_Bi";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-darwin-build/releases/download/v7.0.2-1/ffmpeg-xcframeworks_v7.0.2-1_ios-universal-video-default.tar.gz";
      hash = "sha256-HAzrMHDER2yjzfMlFVumI3EvYxxiHCvhCFPpwVr9e6k=";
    };
  }
  {
    name = "N-V-__8AAOlodAHGt7-GT4PEp7D9IUyn_s8OrksnPMqZJ7SE";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-android-build/releases/download/v7.1-3/default-arm64-v8a.jar";
      hash = "sha256-PAHLd0/IDRlCrLFJHtx7zaf40b90LZAX8HWrogY6BMA=";
    };
  }
  {
    name = "N-V-__8AAPFCRgFgwZzHB_MBjLzsyWgI450E1fkIIBTTsOm_";
    path = fetchzip {
      url = "https://github.com/gungun974/melodink-ffmpeg-android-build/releases/download/v7.1-3/default-x86.jar";
      hash = "sha256-oxDxqQW3oomsN1VZItFIBh7H5cUelkxuD/nkfWpsnb4=";
    };
  }
  {
    name = "N-V-__8AAPu4vwC_P5AHlL_kEON58uGgrDcJSjGq9Hc5yadh";
    path = fetchzip {
      url = "https://github.com/mackron/miniaudio/archive/refs/tags/0.11.23.zip";
      hash = "sha256-ZrfKw5a3AtIER2btCKWhuvygasNaHNf9EURf1Kv96Vc=";
    };
  }
]
